### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by Elvisthegreat** [Elvisthegreat/My-First-Agile-Project#3]
In order to **to sign for up the love running community** as a **user**, I can **write and submit a poll of message**

# Acceptance Criteria
* You should you use the poll message textbox to add your ideas
* You should make sure the langauge you write with is well clear and understandable
* Remember to tickle the radio button before submission

# Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
