### ISSUE TITLE
user story

### ISSUE THREAD

**Issue by Elvisthegreat** [Elvisthegreat/My-First-Agile-Project#4]
In order to **to sign for up the love running community** as a **user**, I can **write and submit a poll of message**
# Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function

**Comment by Elvisthegreat** [comment]
This is completed
